### ISSUE TITLE
Unable to Build Docker Image

### ISSUE THREAD

**Issue by x0axz** [streetcred-id/docker#2]
```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libindy : Depends: libsodium18 but it is not installable
E: Unable to correct problems, you have held broken packages.
The command '/bin/sh -c apt-get update -y && apt-get install -y --allow-unauthenticated         libindy         libsovtoken         dotnet-sdk-3.1' returned a non-zero code: 100
```

**Comment by tmarkovski** [comment]
Looks like libindy stable stream is broken in terms of dependencies. If you use the `master` stream, it should work.

`RUN add-apt-repository "deb https://repo.sovrin.org/sdk/deb xenial master"`

Alternatively, you can just use the pre-built images in your docker directly
`FROM streetcred/dotnet-indy:latest`

**Comment by x0axz** [comment]
Response by @tmarkovski ->
 
> Seems an issue with libindy deps in the stable stream. Switching to master I was able to build the dockerfile
> Change this line to master from stable - RUN add-apt-repository "deb https://repo.sovrin.org/sdk/deb xenial master"
